# Site settings
title: "{Doky's Blog}"
email: makingfunk0@gmail.com
description: "{Doky's Blog} Python Dev Page"
baseurl: ""
url: "https://kimdoky.github.io/"
title_description: "Python, Django, Web Dev"
title_image: "img/main.jpg"
google_analytics: "UA-145839071-1"
disqus_account: dokyung_kim
github_repository: https://github.com/KimDoKy/
post_limit: 5

# Social usernames/URLs
github_username:  KimDoKy
instagram_username: makingfunk
facebook_link: https://www.facebook.com/dokyung.kim.752

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://www.facebook.com/dokyung.kim.752\">Doky</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/KimDoKy/\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]

# Disqus Comments
---
layout: default
comments: true
---
